// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"net/http"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/client/alert_rule"
	"terraform-provider-logicmonitor/client/collector"
	"terraform-provider-logicmonitor/client/collector_group"
	"terraform-provider-logicmonitor/client/dashboard"
	"terraform-provider-logicmonitor/client/dashboard_group"
	"terraform-provider-logicmonitor/client/data_resource_aws_external_id"
	"terraform-provider-logicmonitor/client/datasource"
	"terraform-provider-logicmonitor/client/device"
	"terraform-provider-logicmonitor/client/device_group"
	"terraform-provider-logicmonitor/client/device_group_cluster_alert_conf"
	"terraform-provider-logicmonitor/client/escalation_chain"
	"terraform-provider-logicmonitor/client/report_group"
	"terraform-provider-logicmonitor/client/role"
	"terraform-provider-logicmonitor/client/sdt"
	"terraform-provider-logicmonitor/client/website"
	"terraform-provider-logicmonitor/client/website_group"
	"terraform-provider-logicmonitor/client/widget"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/santaba/rest"
)

// DefaultSchees are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// Config information for LogicMonitorRESTAPI client
type Config struct {
	AccessKey    *string
	AccessID     *string
	BulkResource *bool
	TransportCfg *TransportConfig
}

// NewConfig create a new empty client Config
func NewConfig() *Config {
	return &Config{
		TransportCfg: DefaultTransportConfig(),
	}
}

// SetAccessID for the client Config
func (c *Config) SetAccessID(accessID *string) {
	c.AccessID = accessID
}

// SetAccessKey for the client Config
func (c *Config) SetAccessKey(accessKey *string) {
	c.AccessKey = accessKey
}

// SetAccountDomain for the client Config
func (c *Config) SetAccountDomain(accountDomain *string) {
	if c.TransportCfg == nil {
		c.TransportCfg = DefaultTransportConfig()
	}
	domain := *accountDomain
	c.TransportCfg = c.TransportCfg.WithHost(domain)
}

// Set Bulk import feature
func (c *Config) SetBulkResource(bulkResource *bool) {
	c.BulkResource = bulkResource
}

// New creates a new logic monitor r e s t API client
func New(c *Config, httpClient *http.Client) *LogicMonitorRESTAPI {
	var transport *httptransport.Runtime
	if httpClient != nil {
		transport = httptransport.NewWithClient(c.TransportCfg.Host, c.TransportCfg.BasePath, c.TransportCfg.Schemes, httpClient)
	} else {
		transport = httptransport.New(c.TransportCfg.Host, c.TransportCfg.BasePath, c.TransportCfg.Schemes)
	}
	authInfo := LMv1Auth(*c.AccessID, *c.AccessKey)

	cli := new(LogicMonitorRESTAPI)
	cli.Transport = transport
	cli.accessID = *c.AccessID
	cli.accessKey = *c.AccessKey
	cli.httpClient = httpClient
	cli.transportCfg = c.TransportCfg

	cli.AlertRule = alert_rule.New(transport, strfmt.Default, authInfo)

	cli.Collector = collector.New(transport, strfmt.Default, authInfo)

	cli.CollectorGroup = collector_group.New(transport, strfmt.Default, authInfo)

	cli.Dashboard = dashboard.New(transport, strfmt.Default, authInfo)

	cli.DashboardGroup = dashboard_group.New(transport, strfmt.Default, authInfo)

	cli.DataResourceAwsExternalID = data_resource_aws_external_id.New(transport, strfmt.Default, authInfo)

	cli.Datasource = datasource.New(transport, strfmt.Default, authInfo)

	cli.Device = device.New(transport, strfmt.Default, authInfo)

	cli.DeviceGroup = device_group.New(transport, strfmt.Default, authInfo)

	cli.DeviceGroupClusterAlertConf = device_group_cluster_alert_conf.New(transport, strfmt.Default, authInfo)

	cli.EscalationChain = escalation_chain.New(transport, strfmt.Default, authInfo)

	cli.ReportGroup = report_group.New(transport, strfmt.Default, authInfo)

	cli.Role = role.New(transport, strfmt.Default, authInfo)

	cli.Sdt = sdt.New(transport, strfmt.Default, authInfo)

	cli.Website = website.New(transport, strfmt.Default, authInfo)

	cli.WebsiteGroup = website_group.New(transport, strfmt.Default, authInfo)

	cli.Widget = widget.New(transport, strfmt.Default, authInfo)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// LogicMonitorRESTAPI is a client for logic monitor r e s t API
type LogicMonitorRESTAPI struct {
	AlertRule *alert_rule.Client

	Collector *collector.Client

	CollectorGroup *collector_group.Client

	Dashboard *dashboard.Client

	DashboardGroup *dashboard_group.Client

	DataResourceAwsExternalID *data_resource_aws_external_id.Client

	Datasource *datasource.Client

	Device *device.Client

	DeviceGroup *device_group.Client

	DeviceGroupClusterAlertConf *device_group_cluster_alert_conf.Client

	EscalationChain *escalation_chain.Client

	ReportGroup *report_group.Client

	Role *role.Client

	Sdt *sdt.Client

	Website *website.Client

	WebsiteGroup *website_group.Client

	Widget *widget.Client

	Transport runtime.ClientTransport

	accessID     string
	accessKey    string
	httpClient   *http.Client
	transportCfg *TransportConfig
}

// SetTransport changes the transport on the client and all its subresources
func (c *LogicMonitorRESTAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.AlertRule.SetTransport(transport)

	c.Collector.SetTransport(transport)

	c.CollectorGroup.SetTransport(transport)

	c.Dashboard.SetTransport(transport)

	c.DashboardGroup.SetTransport(transport)

	c.DataResourceAwsExternalID.SetTransport(transport)

	c.Datasource.SetTransport(transport)

	c.Device.SetTransport(transport)

	c.DeviceGroup.SetTransport(transport)

	c.DeviceGroupClusterAlertConf.SetTransport(transport)

	c.EscalationChain.SetTransport(transport)

	c.ReportGroup.SetTransport(transport)

	c.Role.SetTransport(transport)

	c.Sdt.SetTransport(transport)

	c.Website.SetTransport(transport)

	c.WebsiteGroup.SetTransport(transport)

	c.Widget.SetTransport(transport)

}

func LMv1Auth(accessId, accessKey string) runtime.ClientAuthInfoWriter {
	return runtime.ClientAuthInfoWriterFunc(func(r runtime.ClientRequest, _ strfmt.Registry) error {
		var bodyParts [][]byte
		if r.GetBodyParam() != nil {
			body, err := EncodeLMv1JSONBody(r.GetBodyParam())
			if err != nil {
				return err
			}
			if len(body) > 0 {
				bodyParts = append(bodyParts, body)
			}
		}
		if r.GetFileParam() != nil {
			for _, files := range r.GetFileParam() {
				for i, file := range files {
					buf := bytes.NewBuffer(nil)
					buf.ReadFrom(file)
					bodyParts = append(bodyParts, buf.Bytes())
					file = runtime.NamedReader(file.Name(), bytes.NewReader(buf.Bytes()))
					files[i] = file
				}
			}
		}
		authHeader := SignLMv1WithBodyParts(accessId, accessKey, r.GetMethod(), r.GetPath(), bodyParts)
		r.SetHeaderParam("Authorization", authHeader)
		return r.SetHeaderParam("X-version", "3")
	})
}
