// Code generated by go-swagger; DO NOT EDIT.

package device_group_cluster_alert_conf

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/models"
)

// GetDeviceGroupClusterAlertConfListReader is a Reader for the GetDeviceGroupClusterAlertConfList structure.
type GetDeviceGroupClusterAlertConfListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceGroupClusterAlertConfListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceGroupClusterAlertConfListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetDeviceGroupClusterAlertConfListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDeviceGroupClusterAlertConfListOK creates a GetDeviceGroupClusterAlertConfListOK with default headers values
func NewGetDeviceGroupClusterAlertConfListOK() *GetDeviceGroupClusterAlertConfListOK {
	return &GetDeviceGroupClusterAlertConfListOK{}
}

/*
GetDeviceGroupClusterAlertConfListOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetDeviceGroupClusterAlertConfListOK struct {
	Payload *models.DeviceGroupClusterAlertConfPaginationResponse
}

func (o *GetDeviceGroupClusterAlertConfListOK) Error() string {
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf][%d] getDeviceGroupClusterAlertConfListOK  %+v", 200, o.Payload)
}
func (o *GetDeviceGroupClusterAlertConfListOK) GetPayload() *models.DeviceGroupClusterAlertConfPaginationResponse {
	return o.Payload
}

func (o *GetDeviceGroupClusterAlertConfListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceGroupClusterAlertConfPaginationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeviceGroupClusterAlertConfListDefault creates a GetDeviceGroupClusterAlertConfListDefault with default headers values
func NewGetDeviceGroupClusterAlertConfListDefault(code int) *GetDeviceGroupClusterAlertConfListDefault {
	return &GetDeviceGroupClusterAlertConfListDefault{
		_statusCode: code,
	}
}

/*
GetDeviceGroupClusterAlertConfListDefault describes a response with status code -1, with default header values.

Error
*/
type GetDeviceGroupClusterAlertConfListDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get device group cluster alert conf list default response
func (o *GetDeviceGroupClusterAlertConfListDefault) Code() int {
	return o._statusCode
}

func (o *GetDeviceGroupClusterAlertConfListDefault) Error() string {
	return fmt.Sprintf("[GET /device/groups/{deviceGroupId}/clusterAlertConf][%d] getDeviceGroupClusterAlertConfList default  %+v", o._statusCode, o.Payload)
}
func (o *GetDeviceGroupClusterAlertConfListDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetDeviceGroupClusterAlertConfListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
