// Code generated by go-swagger; DO NOT EDIT.

package sdt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"terraform-provider-logicmonitor/common"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/models"
)

// NewAddSdtParams creates a new AddSdtParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddSdtParams() *AddSdtParams {
	return &AddSdtParams{
		timeout: common.DefaultTimeout,
	}
}

// NewAddSdtParamsWithTimeout creates a new AddSdtParams object
// with the ability to set a timeout on a request.
func NewAddSdtParamsWithTimeout(timeout time.Duration) *AddSdtParams {
	return &AddSdtParams{
		timeout: timeout,
	}
}

// NewAddSdtParamsWithContext creates a new AddSdtParams object
// with the ability to set a context for a request.
func NewAddSdtParamsWithContext(ctx context.Context) *AddSdtParams {
	return &AddSdtParams{
		Context: ctx,
	}
}

// NewAddSdtParamsWithHTTPClient creates a new AddSdtParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddSdtParamsWithHTTPClient(client *http.Client) *AddSdtParams {
	return &AddSdtParams{
		HTTPClient: client,
	}
}

/*
AddSdtParams contains all the parameters to send to the API endpoint

	for the add sdt operation.

	Typically these are written to a http.Request.
*/
type AddSdtParams struct {

	// Body.
	Body *models.Sdt

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add sdt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSdtParams) WithDefaults() *AddSdtParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add sdt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSdtParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add sdt params
func (o *AddSdtParams) WithTimeout(timeout time.Duration) *AddSdtParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add sdt params
func (o *AddSdtParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add sdt params
func (o *AddSdtParams) WithContext(ctx context.Context) *AddSdtParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add sdt params
func (o *AddSdtParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add sdt params
func (o *AddSdtParams) WithHTTPClient(client *http.Client) *AddSdtParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add sdt params
func (o *AddSdtParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add sdt params
func (o *AddSdtParams) WithBody(body *models.Sdt) *AddSdtParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add sdt params
func (o *AddSdtParams) SetBody(body *models.Sdt) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddSdtParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
