// Code generated by go-swagger; DO NOT EDIT.

package sdt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"terraform-provider-logicmonitor/common"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSdtByIDParams creates a new DeleteSdtByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSdtByIDParams() *DeleteSdtByIDParams {
	return &DeleteSdtByIDParams{
		timeout: common.DefaultTimeout,
	}
}

// NewDeleteSdtByIDParamsWithTimeout creates a new DeleteSdtByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteSdtByIDParamsWithTimeout(timeout time.Duration) *DeleteSdtByIDParams {
	return &DeleteSdtByIDParams{
		timeout: timeout,
	}
}

// NewDeleteSdtByIDParamsWithContext creates a new DeleteSdtByIDParams object
// with the ability to set a context for a request.
func NewDeleteSdtByIDParamsWithContext(ctx context.Context) *DeleteSdtByIDParams {
	return &DeleteSdtByIDParams{
		Context: ctx,
	}
}

// NewDeleteSdtByIDParamsWithHTTPClient creates a new DeleteSdtByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSdtByIDParamsWithHTTPClient(client *http.Client) *DeleteSdtByIDParams {
	return &DeleteSdtByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteSdtByIDParams contains all the parameters to send to the API endpoint

	for the delete sdt by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteSdtByIDParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete sdt by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSdtByIDParams) WithDefaults() *DeleteSdtByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete sdt by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSdtByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete sdt by Id params
func (o *DeleteSdtByIDParams) WithTimeout(timeout time.Duration) *DeleteSdtByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sdt by Id params
func (o *DeleteSdtByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sdt by Id params
func (o *DeleteSdtByIDParams) WithContext(ctx context.Context) *DeleteSdtByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sdt by Id params
func (o *DeleteSdtByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sdt by Id params
func (o *DeleteSdtByIDParams) WithHTTPClient(client *http.Client) *DeleteSdtByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sdt by Id params
func (o *DeleteSdtByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete sdt by Id params
func (o *DeleteSdtByIDParams) WithID(id string) *DeleteSdtByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete sdt by Id params
func (o *DeleteSdtByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSdtByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
