// Code generated by go-swagger; DO NOT EDIT.

package sdt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/models"
)

// DeleteSdtByIDReader is a Reader for the DeleteSdtByID structure.
type DeleteSdtByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSdtByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSdtByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSdtByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSdtByIDOK creates a DeleteSdtByIDOK with default headers values
func NewDeleteSdtByIDOK() *DeleteSdtByIDOK {
	return &DeleteSdtByIDOK{}
}

/*
DeleteSdtByIDOK describes a response with status code 200, with default header values.

Successful operation
*/
type DeleteSdtByIDOK struct {
	Payload interface{}
}

func (o *DeleteSdtByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /sdt/sdts/{id}][%d] deleteSdtByIdOK  %+v", 200, o.Payload)
}
func (o *DeleteSdtByIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteSdtByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSdtByIDDefault creates a DeleteSdtByIDDefault with default headers values
func NewDeleteSdtByIDDefault(code int) *DeleteSdtByIDDefault {
	return &DeleteSdtByIDDefault{
		_statusCode: code,
	}
}

/*
DeleteSdtByIDDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteSdtByIDDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete sdt by Id default response
func (o *DeleteSdtByIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSdtByIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /sdt/sdts/{id}][%d] deleteSdtById default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteSdtByIDDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSdtByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
