// Code generated by go-swagger; DO NOT EDIT.

package sdt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/models"
)

// GetSdtByIDReader is a Reader for the GetSdtByID structure.
type GetSdtByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSdtByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSdtByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetSdtByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSdtByIDOK creates a GetSdtByIDOK with default headers values
func NewGetSdtByIDOK() *GetSdtByIDOK {
	return &GetSdtByIDOK{}
}

/*
GetSdtByIDOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetSdtByIDOK struct {
	Payload *models.Sdt
}

func (o *GetSdtByIDOK) Error() string {
	return fmt.Sprintf("[GET /sdt/sdts/{id}][%d] getSdtByIdOK  %+v", 200, o.Payload)
}
func (o *GetSdtByIDOK) GetPayload() *models.Sdt {
	return o.Payload
}

func (o *GetSdtByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Sdt)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSdtByIDDefault creates a GetSdtByIDDefault with default headers values
func NewGetSdtByIDDefault(code int) *GetSdtByIDDefault {
	return &GetSdtByIDDefault{
		_statusCode: code,
	}
}

/*
GetSdtByIDDefault describes a response with status code -1, with default header values.

Error
*/
type GetSdtByIDDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get sdt by Id default response
func (o *GetSdtByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetSdtByIDDefault) Error() string {
	return fmt.Sprintf("[GET /sdt/sdts/{id}][%d] getSdtById default  %+v", o._statusCode, o.Payload)
}
func (o *GetSdtByIDDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSdtByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
