// Code generated by go-swagger; DO NOT EDIT.

package sdt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"terraform-provider-logicmonitor/common"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/models"
)

// NewPatchSdtByIDParams creates a new PatchSdtByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchSdtByIDParams() *PatchSdtByIDParams {
	return &PatchSdtByIDParams{
		timeout: common.DefaultTimeout,
	}
}

// NewPatchSdtByIDParamsWithTimeout creates a new PatchSdtByIDParams object
// with the ability to set a timeout on a request.
func NewPatchSdtByIDParamsWithTimeout(timeout time.Duration) *PatchSdtByIDParams {
	return &PatchSdtByIDParams{
		timeout: timeout,
	}
}

// NewPatchSdtByIDParamsWithContext creates a new PatchSdtByIDParams object
// with the ability to set a context for a request.
func NewPatchSdtByIDParamsWithContext(ctx context.Context) *PatchSdtByIDParams {
	return &PatchSdtByIDParams{
		Context: ctx,
	}
}

// NewPatchSdtByIDParamsWithHTTPClient creates a new PatchSdtByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchSdtByIDParamsWithHTTPClient(client *http.Client) *PatchSdtByIDParams {
	return &PatchSdtByIDParams{
		HTTPClient: client,
	}
}

/*
PatchSdtByIDParams contains all the parameters to send to the API endpoint

	for the patch sdt by Id operation.

	Typically these are written to a http.Request.
*/
type PatchSdtByIDParams struct {

	// Body.
	Body *models.Sdt

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch sdt by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchSdtByIDParams) WithDefaults() *PatchSdtByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch sdt by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchSdtByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch sdt by Id params
func (o *PatchSdtByIDParams) WithTimeout(timeout time.Duration) *PatchSdtByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch sdt by Id params
func (o *PatchSdtByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch sdt by Id params
func (o *PatchSdtByIDParams) WithContext(ctx context.Context) *PatchSdtByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch sdt by Id params
func (o *PatchSdtByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch sdt by Id params
func (o *PatchSdtByIDParams) WithHTTPClient(client *http.Client) *PatchSdtByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch sdt by Id params
func (o *PatchSdtByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch sdt by Id params
func (o *PatchSdtByIDParams) WithBody(body *models.Sdt) *PatchSdtByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch sdt by Id params
func (o *PatchSdtByIDParams) SetBody(body *models.Sdt) {
	o.Body = body
}

// WithID adds the id to the patch sdt by Id params
func (o *PatchSdtByIDParams) WithID(id string) *PatchSdtByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch sdt by Id params
func (o *PatchSdtByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchSdtByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
