// Code generated by go-swagger; DO NOT EDIT.

package sdt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"terraform-provider-logicmonitor/common"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"terraform-provider-logicmonitor/models"
)

// NewUpdateSdtByIDParams creates a new UpdateSdtByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateSdtByIDParams() *UpdateSdtByIDParams {
	return &UpdateSdtByIDParams{
		timeout: common.DefaultTimeout,
	}
}

// NewUpdateSdtByIDParamsWithTimeout creates a new UpdateSdtByIDParams object
// with the ability to set a timeout on a request.
func NewUpdateSdtByIDParamsWithTimeout(timeout time.Duration) *UpdateSdtByIDParams {
	return &UpdateSdtByIDParams{
		timeout: timeout,
	}
}

// NewUpdateSdtByIDParamsWithContext creates a new UpdateSdtByIDParams object
// with the ability to set a context for a request.
func NewUpdateSdtByIDParamsWithContext(ctx context.Context) *UpdateSdtByIDParams {
	return &UpdateSdtByIDParams{
		Context: ctx,
	}
}

// NewUpdateSdtByIDParamsWithHTTPClient creates a new UpdateSdtByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateSdtByIDParamsWithHTTPClient(client *http.Client) *UpdateSdtByIDParams {
	return &UpdateSdtByIDParams{
		HTTPClient: client,
	}
}

/*
UpdateSdtByIDParams contains all the parameters to send to the API endpoint

	for the update sdt by Id operation.

	Typically these are written to a http.Request.
*/
type UpdateSdtByIDParams struct {

	// Body.
	Body *models.Sdt

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update sdt by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSdtByIDParams) WithDefaults() *UpdateSdtByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update sdt by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSdtByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update sdt by Id params
func (o *UpdateSdtByIDParams) WithTimeout(timeout time.Duration) *UpdateSdtByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update sdt by Id params
func (o *UpdateSdtByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update sdt by Id params
func (o *UpdateSdtByIDParams) WithContext(ctx context.Context) *UpdateSdtByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update sdt by Id params
func (o *UpdateSdtByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update sdt by Id params
func (o *UpdateSdtByIDParams) WithHTTPClient(client *http.Client) *UpdateSdtByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update sdt by Id params
func (o *UpdateSdtByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update sdt by Id params
func (o *UpdateSdtByIDParams) WithBody(body *models.Sdt) *UpdateSdtByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update sdt by Id params
func (o *UpdateSdtByIDParams) SetBody(body *models.Sdt) {
	o.Body = body
}

// WithID adds the id to the update sdt by Id params
func (o *UpdateSdtByIDParams) WithID(id string) *UpdateSdtByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update sdt by Id params
func (o *UpdateSdtByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSdtByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
