// Code generated by go-swagger; DO NOT EDIT.

package collector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCollectorDownloadTokenParams creates a new GetCollectorDownloadTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectorDownloadTokenParams() *GetCollectorDownloadTokenParams {
	return &GetCollectorDownloadTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectorDownloadTokenParamsWithTimeout creates a new GetCollectorDownloadTokenParams object
// with the ability to set a timeout on a request.
func NewGetCollectorDownloadTokenParamsWithTimeout(timeout time.Duration) *GetCollectorDownloadTokenParams {
	return &GetCollectorDownloadTokenParams{
		timeout: timeout,
	}
}

// NewGetCollectorDownloadTokenParamsWithContext creates a new GetCollectorDownloadTokenParams object
// with the ability to set a context for a request.
func NewGetCollectorDownloadTokenParamsWithContext(ctx context.Context) *GetCollectorDownloadTokenParams {
	return &GetCollectorDownloadTokenParams{
		Context: ctx,
	}
}

// NewGetCollectorDownloadTokenParamsWithHTTPClient creates a new GetCollectorDownloadTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectorDownloadTokenParamsWithHTTPClient(client *http.Client) *GetCollectorDownloadTokenParams {
	return &GetCollectorDownloadTokenParams{
		HTTPClient: client,
	}
}

/* GetCollectorDownloadTokenParams contains all the parameters to send to the API endpoint
   for the get collector download token operation.

   Typically these are written to a http.Request.
*/
type GetCollectorDownloadTokenParams struct {

	// ID.
	//
	// Format: int32
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collector download token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectorDownloadTokenParams) WithDefaults() *GetCollectorDownloadTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collector download token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectorDownloadTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collector download token params
func (o *GetCollectorDownloadTokenParams) WithTimeout(timeout time.Duration) *GetCollectorDownloadTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collector download token params
func (o *GetCollectorDownloadTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collector download token params
func (o *GetCollectorDownloadTokenParams) WithContext(ctx context.Context) *GetCollectorDownloadTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collector download token params
func (o *GetCollectorDownloadTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collector download token params
func (o *GetCollectorDownloadTokenParams) WithHTTPClient(client *http.Client) *GetCollectorDownloadTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collector download token params
func (o *GetCollectorDownloadTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get collector download token params
func (o *GetCollectorDownloadTokenParams) WithID(id int32) *GetCollectorDownloadTokenParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get collector download token params
func (o *GetCollectorDownloadTokenParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectorDownloadTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
