// Code generated by go-swagger; DO NOT EDIT.

package datasource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"terraform-provider-logicmonitor/common"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteDatasourceByIDParams creates a new DeleteDatasourceByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDatasourceByIDParams() *DeleteDatasourceByIDParams {
	return &DeleteDatasourceByIDParams{
		timeout: common.DefaultTimeout,
	}
}

// NewDeleteDatasourceByIDParamsWithTimeout creates a new DeleteDatasourceByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteDatasourceByIDParamsWithTimeout(timeout time.Duration) *DeleteDatasourceByIDParams {
	return &DeleteDatasourceByIDParams{
		timeout: timeout,
	}
}

// NewDeleteDatasourceByIDParamsWithContext creates a new DeleteDatasourceByIDParams object
// with the ability to set a context for a request.
func NewDeleteDatasourceByIDParamsWithContext(ctx context.Context) *DeleteDatasourceByIDParams {
	return &DeleteDatasourceByIDParams{
		Context: ctx,
	}
}

// NewDeleteDatasourceByIDParamsWithHTTPClient creates a new DeleteDatasourceByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDatasourceByIDParamsWithHTTPClient(client *http.Client) *DeleteDatasourceByIDParams {
	return &DeleteDatasourceByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteDatasourceByIDParams contains all the parameters to send to the API endpoint

	for the delete datasource by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteDatasourceByIDParams struct {

	// ID.
	//
	// Format: int32
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete datasource by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDatasourceByIDParams) WithDefaults() *DeleteDatasourceByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete datasource by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDatasourceByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) WithTimeout(timeout time.Duration) *DeleteDatasourceByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) WithContext(ctx context.Context) *DeleteDatasourceByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) WithHTTPClient(client *http.Client) *DeleteDatasourceByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) WithID(id int32) *DeleteDatasourceByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete datasource by Id params
func (o *DeleteDatasourceByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDatasourceByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
