//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"log"
	"terraform-provider-logicmonitor/client"
	"terraform-provider-logicmonitor/client/data_resource_aws_external_id"
	"terraform-provider-logicmonitor/logicmonitor/schemata"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

/*
DataResourceAwsExternalID data resource aws external id API
*/

func DataResourceAwsExternalID() *schema.Resource {
	return &schema.Resource{
		ReadContext: getAwsExternalId,
		Schema:      schemata.AwsExternalIDSchema(),
	}
}

func getAwsExternalId(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := data_resource_aws_external_id.NewGetAwsExternalIDParams()

	client := m.(*client.LogicMonitorRESTAPI)

	resp, err := client.DataResourceAwsExternalID.GetAwsExternalID(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetAwsExternalIDResourceData(d, respModel)
	return diags
}
