//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"terraform-provider-logicmonitor/client"
	"terraform-provider-logicmonitor/client/device_group_cluster_alert_conf"
	"terraform-provider-logicmonitor/logicmonitor/schemata"
	"terraform-provider-logicmonitor/logicmonitor/utils"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

/*
DeviceGroupClusterAlertConf device group cluster alert conf API
*/

func DeviceGroupClusterAlertConf() *schema.Resource {
	return &schema.Resource{
		CreateContext: addDeviceGroupClusterAlertConf,
		DeleteContext: deleteDeviceGroupClusterAlertConfById,
		ReadContext:   getDeviceGroupClusterAlertConfById,
		UpdateContext: updateDeviceGroupClusterAlertConfById,
		Importer: &schema.ResourceImporter{
			State: resourceDeviceGroupClusterAlertConfStateImporter,
		},
		Schema: schemata.DeviceGroupClusterAlertConfSchema(),
	}
}

func DataResourceDeviceGroupClusterAlertConf() *schema.Resource {
	return &schema.Resource{
		ReadContext: getDeviceGroupClusterAlertConfList,
		Schema:      schemata.DataSourceDeviceGroupClusterAlertConfSchema(),
	}
}

func addDeviceGroupClusterAlertConf(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	model := schemata.DeviceGroupClusterAlertConfModel(d)
	params := device_group_cluster_alert_conf.NewAddDeviceGroupClusterAlertConfParams()

	params.SetBody(model)

	deviceGroupIdVal, deviceGroupIdIsSet := d.GetOk("device_group_id")
	if deviceGroupIdIsSet {
		i := int32(deviceGroupIdVal.(int))
		params.DeviceGroupID = i
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - deviceGroupId")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.LogicMonitorRESTAPI)

	resp, err := client.DeviceGroupClusterAlertConf.AddDeviceGroupClusterAlertConf(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetDeviceGroupClusterAlertConfResourceData(d, respModel)
	d.SetId(strconv.Itoa(int(resp.Payload.ID)))

	return diags
}

func deleteDeviceGroupClusterAlertConfById(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := device_group_cluster_alert_conf.NewDeleteDeviceGroupClusterAlertConfByIDParams()

	deviceGroupIdVal, deviceGroupIdIsSet := d.GetOk("device_group_id")
	if deviceGroupIdIsSet {
		i := int32(deviceGroupIdVal.(int))
		params.DeviceGroupID = i
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - deviceGroupId")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		id, _ := strconv.Atoi(idVal.(string))
		params.ID = int32(id)

	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.LogicMonitorRESTAPI)

	resp, err := client.DeviceGroupClusterAlertConf.DeleteDeviceGroupClusterAlertConfByID(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	d.SetId("")
	return diags
}

func getDeviceGroupClusterAlertConfById(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := device_group_cluster_alert_conf.NewGetDeviceGroupClusterAlertConfByIDParams()

	deviceGroupIdVal, deviceGroupIdIsSet := d.GetOk("device_group_id")
	if deviceGroupIdIsSet {
		i := int32(deviceGroupIdVal.(int))
		params.DeviceGroupID = i
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - deviceGroupId")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		id, _ := strconv.Atoi(idVal.(string))
		params.ID = int32(id)

	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	client := m.(*client.LogicMonitorRESTAPI)

	resp, err := client.DeviceGroupClusterAlertConf.GetDeviceGroupClusterAlertConfByID(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetDeviceGroupClusterAlertConfResourceData(d, respModel)
	return diags
}

func getDeviceGroupClusterAlertConfList(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics

	params := device_group_cluster_alert_conf.NewGetDeviceGroupClusterAlertConfListParams()

	filterVal, filterIsSet := d.GetOk("filter")
	if filterIsSet {
		stringVal := filterVal.(string)
		params.Filter = &stringVal
	}

	client := m.(*client.LogicMonitorRESTAPI)

	resp, err := client.DeviceGroupClusterAlertConf.GetDeviceGroupClusterAlertConfList(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	if len(respModel.Items) == 0 {
		diags = append(diags, diag.Errorf("no DeviceGroupClusterAlertConf found")...)
	} else {
		result := respModel.Items[0]
		d.SetId(strconv.Itoa(int(result.ID)))
		schemata.SetDeviceGroupClusterAlertConfResourceData(d, result)
	}
	return diags
}

func updateDeviceGroupClusterAlertConfById(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	d.Partial(true)

	model := schemata.DeviceGroupClusterAlertConfModel(d)
	params := device_group_cluster_alert_conf.NewUpdateDeviceGroupClusterAlertConfByIDParams()

	params.SetBody(model)

	deviceGroupIdVal, deviceGroupIdIsSet := d.GetOk("device_group_id")
	if deviceGroupIdIsSet {
		i := int32(deviceGroupIdVal.(int))
		params.DeviceGroupID = i
	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - deviceGroupId")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	idVal, idIsSet := d.GetOk("id")
	if idIsSet {
		id, _ := strconv.Atoi(idVal.(string))
		params.ID = int32(id)

	} else {
		diags = append(diags, diag.Errorf("unexpected: Missing parameter - id")...)
		diags = append(diags, diag.Errorf("ending operation")...)
		return diags
	}

	// list of available properties
	props := schemata.GetDeviceGroupClusterAlertConfPropertyFields()

	// loops through array of properties to see which one has changed, the ones that did not change are removed from the list
	for _, v := range props {
		if d.HasChange(v) {
		} else {
			props = utils.Remove(props, v)
		}
	}

	client := m.(*client.LogicMonitorRESTAPI)

	// makes a bulk update for all properties that were changed
	resp, err := client.DeviceGroupClusterAlertConf.UpdateDeviceGroupClusterAlertConfByID(params)
	log.Printf("[TRACE] response: %v", resp)
	if err != nil {
		diags = append(diags, diag.Errorf("unexpected: %s", err)...)
		return diags
	}

	respModel := resp.GetPayload()
	schemata.SetDeviceGroupClusterAlertConfResourceData(d, respModel)
	d.Partial(false)

	return diags
}

func resourceDeviceGroupClusterAlertConfStateImporter(d *schema.ResourceData, m interface{}) ([]*schema.ResourceData, error) {
	client := m.(*client.LogicMonitorRESTAPI)

	// if user provides an ID, we will add the device group cluster alert conf directly
	if utils.IsID(d.Id()) {
		id, err := strconv.Atoi(d.Id())
		if err != nil {
			return nil, err
		}

		params := device_group_cluster_alert_conf.NewGetDeviceGroupClusterAlertConfByIDParams()
		params.SetID(int32(id))

		resp, err := client.DeviceGroupClusterAlertConf.GetDeviceGroupClusterAlertConfByID(params)
		log.Printf("[TRACE] response: %v", resp)
		if err != nil {
			log.Printf("Failed to find device group cluster alert conf %q", err)
			return nil, err
		}

		respModel := resp.GetPayload()
		schemata.SetDeviceGroupClusterAlertConfResourceData(d, respModel)
	} else {
		// find device_group_cluster_alert_conf by name
		params := device_group_cluster_alert_conf.NewGetDeviceGroupClusterAlertConfListParams()
		filter := fmt.Sprintf("name:\"%s\"", d.Id())
		params.SetFilter(&filter)

		resp, err := client.DeviceGroupClusterAlertConf.GetDeviceGroupClusterAlertConfList(params)
		log.Printf("[TRACE] response: %v", resp)
		if err != nil {
			err := fmt.Errorf("unexpected: %s", err)
			return nil, err
		}

		if resp.Payload.Total > 1 {
			err := fmt.Errorf("found more than 1 device group cluster alert conf with filter %s, please make the filter more specific or import with ID", filter)
			return nil, err
		} else if resp.Payload.Total == 1 {
			schemata.SetDeviceGroupClusterAlertConfResourceData(d, resp.Payload.Items[0])
			d.SetId(strconv.Itoa(int(resp.Payload.Items[0].ID)))
		} else {
			err := fmt.Errorf("found no device group cluster alert confs with filter '%s'", filter)
			return nil, err
		}
	}
	return []*schema.ResourceData{d}, nil
}
