// Code generated by generate_polymorphic_codegen.py; DO NOT EDIT.

package schemata

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

var widgetTypeToBlock = map[string]string{
			"cgraph": "graph_info",
		"bigNumber": "big_number_info",
		"pieChart": "pie_chart_info",
		"alert": "alert_info",
		"noc": "noc_info",
		"table": "table_info",
}

var widgetAllBlocks = []string{"graph_info", "big_number_info", "pie_chart_info", "alert_info", "noc_info", "table_info"}

func WidgetSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"dashboard_id": {
			Type:     schema.TypeInt,
			Required: true,
		},
		"description": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"id": {
			Type:     schema.TypeString,
			Computed: true,
		},
		"interval": {
			Type:     schema.TypeInt,
			Optional: true,
		},
		"last_updated_by": {
			Type:     schema.TypeString,
			Optional: true,
			Computed: true,
		},
		"last_updated_on": {
			Type:     schema.TypeInt,
			Optional: true,
			Computed: true,
		},
		"name": {
			Type:     schema.TypeString,
			Required: true,
		},
		"support_key_word": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"theme": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"timescale": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"type": {
			Type:     schema.TypeString,
			Required: true,
		},
		"user_permission": {
			Type:     schema.TypeString,
			Optional: true,
			Computed: true,
		},
		"graph_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: graph_info_block_schema(),
			},
		},
		"big_number_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: big_number_info_block_schema(),
			},
		},
		"pie_chart_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: pie_chart_info_block_schema(),
			},
		},
		"alert_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: alert_info_block_schema(),
			},
		},
		"noc_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: noc_info_block_schema(),
			},
		},
		"table_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: table_info_block_schema(),
			},
		},
	}
}

func DataSourceWidgetSchema() map[string]*schema.Schema {
	s := WidgetSchema()
	s["filter"] = &schema.Schema{
		Type:     schema.TypeString,
		Optional: true,
	}
	s["id"] = &schema.Schema{
		Type:     schema.TypeInt,
		Optional: true,
		Computed: true,
	}
	return s
}

func graph_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: custom_flexible_virtual_data_source_ex_object_schema(),
					},
		Required: true,
	},
	"desc": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"global_consolidate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"max_value": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"min_value": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"scale_unit": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"top_x": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"vertical_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"virtual_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: custom_virtual_data_point_object_schema(),
					},
		Optional: true,
	},
	}
}

func big_number_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"big_number_items": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: big_number_item_object_schema(),
					},
		Required: true,
	},
	"counters": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: counter_object_schema(),
					},
		Optional: true,
	},
	"data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: big_number_data_point_object_schema(),
					},
		Required: true,
	},
	"virtual_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: virtual_data_point_object_schema(),
					},
		Optional: true,
	},
	}
}

func pie_chart_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"counters": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: counter_object_schema(),
					},
		Optional: true,
	},
	"data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: pie_chart_data_point_object_schema(),
					},
		Optional: true,
	},
	"group_remaining_as_others": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"hide_zero_percent_slices": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"max_slices_can_be_shown": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"pie_chart_items": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: pie_chart_item_object_schema(),
					},
		Required: true,
	},
	"show_labels_and_lines_on_pc": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"title": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"virtual_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: virtual_data_point_object_schema(),
					},
		Optional: true,
	},
	}
}

func alert_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"clone_widget_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"display_settings": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"filters": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Optional: true,
	},
	"is_support_custom_property": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"parsed_filters": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Optional: true,
	},
	"refresh_frequency": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"support_custom_property": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"widget_color_schema": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func noc_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"ack_checked": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"clone_widget_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"display_column": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"display_critical_alert": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"display_error_alert": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"display_settings": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"display_warn_alert": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"is_support_custom_property": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"items": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: noc_item_base_object_schema(),
					},
		Required: true,
	},
	"sdt_checked": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"sort_by": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"support_custom_property": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"widget_filters": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func table_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"clone_widget_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"columns": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: table_widget_column_object_schema(),
					},
		Required: true,
	},
	"display_settings": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"forecast": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"is_support_custom_property": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"rows": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: table_widget_row_object_schema(),
					},
		Required: true,
	},
	"support_custom_property": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"widget_filters": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func custom_flexible_virtual_data_source_ex_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"consolidate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"display": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"instance_name": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"is_valid_exp": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"is_virtual_datapoint": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Required: true,
	},
	}
}

func custom_virtual_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"custom_graph_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"display": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Optional: true,
	},
	"id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rpn": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func color_threshold_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"level": {
		Type:     schema.TypeInt,
		Required: true,
	},
	"relation": {
		Type:     schema.TypeString,
		Required: true,
	},
	"threshold": {
		Type:     schema.TypeFloat,
		Required: true,
	},
	}
}

func big_number_item_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"bottom_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"change_threshold_color_toggle": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"color_thresholds": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: color_threshold_object_schema(),
					},
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"position": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"right_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rounding": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"use_comma_separators": {
		Type:     schema.TypeBool,
		Required: true,
	},
	}
}

func counter_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"applies_to": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func big_number_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeString,
		Required: true,
	},
	"instance_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"type": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func virtual_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rpn": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func pie_chart_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"aggregate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeString,
		Required: true,
	},
	"glob_mode": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"instance_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"top10": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"type": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func pie_chart_item_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"color": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"legend": {
		Type:     schema.TypeString,
		Required: true,
	},
	}
}

func noc_item_base_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_display_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"group_by": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"instance_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"noc_item_options": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"type": {
		Type:     schema.TypeString,
		Required: true,
	},
	"website_group_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"website_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func table_widget_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"data_point_id": {
		Type:     schema.TypeInt,
		Required: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeString,
		Required: true,
	},
	"is_multiple": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	}
}

func table_widget_column_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"alternate_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: table_widget_data_point_object_schema(),
					},
		Optional: true,
	},
	"column_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"data_point": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"enable_forecast": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"id": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"index": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"position": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"properties_options": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rounding_decimal": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"rpn": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"unit_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func table_widget_instance_cell_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"instance_id": {
		Type:     schema.TypeInt,
		Required: true,
	},
	"instance_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"validation_status_code": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	}
}

func table_widget_row_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"device_display_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"device_id": {
		Type:     schema.TypeInt,
		Required: true,
	},
	"group_full_path": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"group_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"id": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"instances": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: table_widget_instance_cell_object_schema(),
					},
		Optional: true,
	},
	"label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"position": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	}
}


func WidgetCustomizeDiff(_ context.Context, d *schema.ResourceDiff, _ interface{}) error {
	typeValue, err := getTypeAttr(d)
	if err != nil {
		return err
	}
	block, ok := widgetTypeToBlock[typeValue]
	if !ok {
		return fmt.Errorf("unsupported Widget type %q", typeValue)
	}
	blockCount, err := getBlockCount(d, block)
	if err != nil {
		return err
	}
	if blockCount == 0 {
		return fmt.Errorf("block %q is required when type is %q", block, typeValue)
	}
	for _, other := range widgetAllBlocks {
		if other == block {
			continue
		}
		otherCount, err := getBlockCount(d, other)
		if err != nil {
			return err
		}
		if otherCount > 0 {
			return fmt.Errorf("block %q is not allowed when type is %q", other, typeValue)
		}
	}
	return nil
}

func setCommonWidgetFields(d *schema.ResourceData, raw map[string]interface{}) {
	if v, ok := raw["id"]; ok && v != nil {
		switch id := v.(type) {
		case float64:
			d.Set("id", strconv.Itoa(int(id)))
		case int:
			d.Set("id", strconv.Itoa(id))
		case int32:
			d.Set("id", strconv.Itoa(int(id)))
		}
	}
	if v, ok := raw["dashboardId"]; ok && v != nil {
		switch n := v.(type) {
		case float64:
			d.Set("dashboard_id", int(n))
		case int:
			d.Set("dashboard_id", n)
		case int32:
			d.Set("dashboard_id", int(n))
		}
	}
	if v, ok := raw["description"].(string); ok {
		d.Set("description", v)
	}
	if v, ok := raw["interval"]; ok && v != nil {
		switch n := v.(type) {
		case float64:
			d.Set("interval", int(n))
		case int:
			d.Set("interval", n)
		case int32:
			d.Set("interval", int(n))
		}
	}
	if v, ok := raw["lastUpdatedBy"].(string); ok {
		d.Set("last_updated_by", v)
	}
	if v, ok := raw["lastUpdatedOn"]; ok && v != nil {
		switch n := v.(type) {
		case float64:
			d.Set("last_updated_on", int64(n))
		case int:
			d.Set("last_updated_on", int64(n))
		case int64:
			d.Set("last_updated_on", n)
		}
	}
	if v, ok := raw["name"].(string); ok {
		d.Set("name", v)
	}
	if v, ok := raw["supportKeyWord"].(string); ok {
		d.Set("support_key_word", v)
	}
	if v, ok := raw["theme"].(string); ok {
		d.Set("theme", v)
	}
	if v, ok := raw["timescale"].(string); ok {
		d.Set("timescale", v)
	}
	if v, ok := raw["type"].(string); ok {
		d.Set("type", v)
	}
	if v, ok := raw["userPermission"].(string); ok {
		d.Set("user_permission", v)
	}
}

func SetWidgetResourceData(d *schema.ResourceData, raw map[string]interface{}) {
	setCommonWidgetFields(d, raw)
	typeValue, ok := raw["type"].(string)
	if !ok {
		return
	}
	switch typeValue {
	case "cgraph":
		if v, ok := raw["graphInfo"]; ok {
			d.Set("graph_info", []interface{}{apiMapToSnake(v)})
		}
	case "bigNumber":
		if v, ok := raw["bigNumberInfo"]; ok {
			d.Set("big_number_info", []interface{}{apiMapToSnake(v)})
		}
	case "pieChart":
		if v, ok := raw["pieChartInfo"]; ok {
			d.Set("pie_chart_info", []interface{}{apiMapToSnake(v)})
		}
	case "alert":
		block := apiFieldsToSnakeBlock(raw, []string{"cloneWidgetId", "displaySettings", "filters", "isSupportCustomProperty", "parsedFilters", "refreshFrequency", "supportCustomProperty", "widgetColorSchema"})
		d.Set("alert_info", []interface{}{block})
	case "noc":
		block := apiFieldsToSnakeBlock(raw, []string{"ackChecked", "cloneWidgetId", "displayColumn", "displayCriticalAlert", "displayErrorAlert", "displaySettings", "displayWarnAlert", "isSupportCustomProperty", "sdtChecked", "sortBy", "supportCustomProperty", "widgetFilters"})
		if v, ok := raw["items"].([]interface{}); ok {
			block["items"] = apiObjectListToSnake(v)
		}
		d.Set("noc_info", []interface{}{block})
	case "table":
		block := apiFieldsToSnakeBlock(raw, []string{"cloneWidgetId", "displaySettings", "forecast", "isSupportCustomProperty", "supportCustomProperty", "widgetFilters"})
		if v, ok := raw["columns"].([]interface{}); ok {
			block["columns"] = apiObjectListToSnake(v)
		}
		if v, ok := raw["rows"].([]interface{}); ok {
			block["rows"] = apiObjectListToSnake(v)
		}
		d.Set("table_info", []interface{}{block})
	}
}

func FlattenWidgetPayload(d *schema.ResourceData) (map[string]interface{}, error) {
	payload := map[string]interface{}{}
	if v, err := getIntAttr(d, "dashboard_id"); err != nil {
		return nil, err
	} else {
		payload["dashboardId"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "description"); err != nil { return nil, err } else if ok {
		payload["description"] = v
	}
	if v, ok, err := getOptionalIntAttr(d, "interval"); err != nil { return nil, err } else if ok {
		payload["interval"] = v
	}
	if v, err := getStringAttr(d, "name"); err != nil {
		return nil, err
	} else {
		payload["name"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "support_key_word"); err != nil { return nil, err } else if ok {
		payload["supportKeyWord"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "theme"); err != nil { return nil, err } else if ok {
		payload["theme"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "timescale"); err != nil { return nil, err } else if ok {
		payload["timescale"] = v
	}
	if v, err := getStringAttr(d, "type"); err != nil {
		return nil, err
	} else {
		payload["type"] = v
	}
	typeValue, err := getTypeAttr(d)
	if err != nil {
		return nil, err
	}
	switch typeValue {
	case "cgraph":
		block, err := getSingleBlock(d, "graph_info")
		if err != nil {
			return nil, err
		}
		payload["graphInfo"] = tfBlockToAPI(block)
	case "bigNumber":
		block, err := getSingleBlock(d, "big_number_info")
		if err != nil {
			return nil, err
		}
		payload["bigNumberInfo"] = tfBlockToAPI(block)
	case "pieChart":
		block, err := getSingleBlock(d, "pie_chart_info")
		if err != nil {
			return nil, err
		}
		payload["pieChartInfo"] = tfBlockToAPI(block)
	case "alert":
		block, err := getSingleBlock(d, "alert_info")
		if err != nil {
			return nil, err
		}
		if v, err := getIntFromBlock(block, "clone_widget_id"); err == nil {
			payload["cloneWidgetId"] = v
		}
		if v, err := getStringFromBlock(block, "display_settings"); err == nil {
			payload["displaySettings"] = decodeJSONContainerIfPossible(v)
		}
		if v, err := getStringFromBlock(block, "filters"); err == nil {
			payload["filters"] = v
		}
		if v, err := getBoolFromBlock(block, "is_support_custom_property"); err == nil {
			payload["isSupportCustomProperty"] = v
		}
		if v, err := getStringFromBlock(block, "parsed_filters"); err == nil {
			payload["parsedFilters"] = v
		}
		if v, err := getStringFromBlock(block, "refresh_frequency"); err == nil {
			payload["refreshFrequency"] = decodeJSONContainerIfPossible(v)
		}
		if v, err := getBoolFromBlock(block, "support_custom_property"); err == nil {
			payload["supportCustomProperty"] = v
		}
		if v, err := getStringFromBlock(block, "widget_color_schema"); err == nil {
			payload["widgetColorSchema"] = v
		}
	case "noc":
		block, err := getSingleBlock(d, "noc_info")
		if err != nil {
			return nil, err
		}
		if v, err := getBoolFromBlock(block, "ack_checked"); err == nil {
			payload["ackChecked"] = v
		}
		if v, err := getIntFromBlock(block, "clone_widget_id"); err == nil {
			payload["cloneWidgetId"] = v
		}
		if v, err := getIntFromBlock(block, "display_column"); err == nil {
			payload["displayColumn"] = v
		}
		if v, err := getBoolFromBlock(block, "display_critical_alert"); err == nil {
			payload["displayCriticalAlert"] = v
		}
		if v, err := getBoolFromBlock(block, "display_error_alert"); err == nil {
			payload["displayErrorAlert"] = v
		}
		if v, err := getStringFromBlock(block, "display_settings"); err == nil {
			payload["displaySettings"] = decodeJSONContainerIfPossible(v)
		}
		if v, err := getBoolFromBlock(block, "display_warn_alert"); err == nil {
			payload["displayWarnAlert"] = v
		}
		if v, err := getBoolFromBlock(block, "is_support_custom_property"); err == nil {
			payload["isSupportCustomProperty"] = v
		}
		if v, ok := block["items"].([]interface{}); ok {
			payload["items"] = expandObjectListToAPI(v)
		}
		if v, err := getBoolFromBlock(block, "sdt_checked"); err == nil {
			payload["sdtChecked"] = v
		}
		if v, err := getStringFromBlock(block, "sort_by"); err == nil {
			payload["sortBy"] = v
		}
		if v, err := getBoolFromBlock(block, "support_custom_property"); err == nil {
			payload["supportCustomProperty"] = v
		}
		if v, err := getStringFromBlock(block, "widget_filters"); err == nil {
			payload["widgetFilters"] = decodeJSONContainerIfPossible(v)
		}
	case "table":
		block, err := getSingleBlock(d, "table_info")
		if err != nil {
			return nil, err
		}
		if v, err := getIntFromBlock(block, "clone_widget_id"); err == nil {
			payload["cloneWidgetId"] = v
		}
		if v, ok := block["columns"].([]interface{}); ok {
			payload["columns"] = expandObjectListToAPI(v)
		}
		if v, err := getStringFromBlock(block, "display_settings"); err == nil {
			payload["displaySettings"] = decodeJSONContainerIfPossible(v)
		}
		if v, err := getStringFromBlock(block, "forecast"); err == nil {
			payload["forecast"] = decodeJSONContainerIfPossible(v)
		}
		if v, err := getBoolFromBlock(block, "is_support_custom_property"); err == nil {
			payload["isSupportCustomProperty"] = v
		}
		if v, ok := block["rows"].([]interface{}); ok {
			payload["rows"] = expandObjectListToAPI(v)
		}
		if v, err := getBoolFromBlock(block, "support_custom_property"); err == nil {
			payload["supportCustomProperty"] = v
		}
		if v, err := getStringFromBlock(block, "widget_filters"); err == nil {
			payload["widgetFilters"] = decodeJSONContainerIfPossible(v)
		}
	default:
		return nil, fmt.Errorf("unsupported type: %s", typeValue)
	}
	return payload, nil
}
