// Code generated by generate_polymorphic_codegen.py; DO NOT EDIT.

package schemata

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

var widgetTypeToBlock = map[string]string{
			"cgraph": "graph_info",
		"bigNumber": "big_number_info",
		"pieChart": "pie_chart_info",
}

var widgetAllBlocks = []string{"graph_info", "big_number_info", "pie_chart_info"}

func WidgetSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"dashboard_id": {
			Type:     schema.TypeInt,
			Required: true,
		},
		"description": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"id": {
			Type:     schema.TypeString,
			Computed: true,
		},
		"interval": {
			Type:     schema.TypeInt,
			Optional: true,
		},
		"last_updated_by": {
			Type:     schema.TypeString,
			Optional: true,
			Computed: true,
		},
		"last_updated_on": {
			Type:     schema.TypeInt,
			Optional: true,
			Computed: true,
		},
		"name": {
			Type:     schema.TypeString,
			Required: true,
		},
		"support_key_word": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"theme": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"timescale": {
			Type:     schema.TypeString,
			Optional: true,
		},
		"type": {
			Type:     schema.TypeString,
			Required: true,
		},
		"user_permission": {
			Type:     schema.TypeString,
			Optional: true,
			Computed: true,
		},
		"graph_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: graph_info_block_schema(),
			},
		},
		"big_number_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: big_number_info_block_schema(),
			},
		},
		"pie_chart_info": {
			Type:     schema.TypeList,
			Optional: true,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: pie_chart_info_block_schema(),
			},
		},
	}
}

func DataSourceWidgetSchema() map[string]*schema.Schema {
	s := WidgetSchema()
	s["filter"] = &schema.Schema{
		Type:     schema.TypeString,
		Optional: true,
	}
	s["id"] = &schema.Schema{
		Type:     schema.TypeInt,
		Optional: true,
		Computed: true,
	}
	return s
}

func graph_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: custom_flexible_virtual_data_source_ex_object_schema(),
					},
		Required: true,
	},
	"desc": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"global_consolidate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"max_value": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"min_value": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"scale_unit": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"top_x": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"vertical_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"virtual_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: custom_virtual_data_point_object_schema(),
					},
		Optional: true,
	},
	}
}

func big_number_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"big_number_items": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: big_number_item_object_schema(),
					},
		Required: true,
	},
	"counters": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: counter_object_schema(),
					},
		Optional: true,
	},
	"data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: big_number_data_point_object_schema(),
					},
		Required: true,
	},
	"virtual_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: virtual_data_point_object_schema(),
					},
		Optional: true,
	},
	}
}

func pie_chart_info_block_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"counters": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: counter_object_schema(),
					},
		Optional: true,
	},
	"data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: pie_chart_data_point_object_schema(),
					},
		Optional: true,
	},
	"group_remaining_as_others": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"hide_zero_percent_slices": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"max_slices_can_be_shown": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"pie_chart_items": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: pie_chart_item_object_schema(),
					},
		Required: true,
	},
	"show_labels_and_lines_on_pc": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"title": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"virtual_data_points": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: virtual_data_point_object_schema(),
					},
		Optional: true,
	},
	}
}

func custom_flexible_virtual_data_source_ex_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"consolidate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"display": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"instance_name": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Required: true,
	},
	"is_valid_exp": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"is_virtual_datapoint": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Required: true,
	},
	}
}

func custom_virtual_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"custom_graph_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"display": {
		Type:     schema.TypeMap,
		Elem: &schema.Schema{Type: schema.TypeString},
		Optional: true,
	},
	"id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rpn": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func color_threshold_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"level": {
		Type:     schema.TypeInt,
		Required: true,
	},
	"relation": {
		Type:     schema.TypeString,
		Required: true,
	},
	"threshold": {
		Type:     schema.TypeFloat,
		Required: true,
	},
	}
}

func big_number_item_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"bottom_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"change_threshold_color_toggle": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"color_thresholds": {
		Type:     schema.TypeList,
		Elem: &schema.Resource{
						Schema: color_threshold_object_schema(),
					},
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"position": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"right_label": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rounding": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"use_comma_separators": {
		Type:     schema.TypeBool,
		Required: true,
	},
	}
}

func counter_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"applies_to": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func big_number_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeString,
		Required: true,
	},
	"instance_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"type": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func virtual_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"rpn": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func pie_chart_data_point_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"aggregate": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"aggregate_function": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_full_name": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_source_id": {
		Type:     schema.TypeInt,
		Optional: true,
	},
	"device_display_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"device_group_full_path": {
		Type:     schema.TypeString,
		Required: true,
	},
	"glob_mode": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"instance_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"top10": {
		Type:     schema.TypeBool,
		Optional: true,
	},
	"type": {
		Type:     schema.TypeString,
		Optional: true,
	},
	}
}

func pie_chart_item_object_schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
	"color": {
		Type:     schema.TypeString,
		Optional: true,
	},
	"data_point_name": {
		Type:     schema.TypeString,
		Required: true,
	},
	"legend": {
		Type:     schema.TypeString,
		Required: true,
	},
	}
}


func WidgetCustomizeDiff(_ context.Context, d *schema.ResourceDiff, _ interface{}) error {
	typeValue, err := getTypeAttr(d)
	if err != nil {
		return err
	}
	block, ok := widgetTypeToBlock[typeValue]
	if !ok {
		return fmt.Errorf("unsupported Widget type %q", typeValue)
	}
	blockCount, err := getBlockCount(d, block)
	if err != nil {
		return err
	}
	if blockCount == 0 {
		return fmt.Errorf("block %q is required when type is %q", block, typeValue)
	}
	for _, other := range widgetAllBlocks {
		if other == block {
			continue
		}
		otherCount, err := getBlockCount(d, other)
		if err != nil {
			return err
		}
		if otherCount > 0 {
			return fmt.Errorf("block %q is not allowed when type is %q", other, typeValue)
		}
	}
	return nil
}

func setCommonWidgetFields(d *schema.ResourceData, raw map[string]interface{}) {
	if v, ok := raw["id"]; ok && v != nil {
		switch id := v.(type) {
		case float64:
			d.Set("id", strconv.Itoa(int(id)))
		case int:
			d.Set("id", strconv.Itoa(id))
		case int32:
			d.Set("id", strconv.Itoa(int(id)))
		}
	}
	if v, ok := raw["dashboardId"]; ok && v != nil {
		switch n := v.(type) {
		case float64:
			d.Set("dashboard_id", int(n))
		case int:
			d.Set("dashboard_id", n)
		case int32:
			d.Set("dashboard_id", int(n))
		}
	}
	if v, ok := raw["description"].(string); ok {
		d.Set("description", v)
	}
	if v, ok := raw["interval"]; ok && v != nil {
		switch n := v.(type) {
		case float64:
			d.Set("interval", int(n))
		case int:
			d.Set("interval", n)
		case int32:
			d.Set("interval", int(n))
		}
	}
	if v, ok := raw["lastUpdatedBy"].(string); ok {
		d.Set("last_updated_by", v)
	}
	if v, ok := raw["lastUpdatedOn"]; ok && v != nil {
		switch n := v.(type) {
		case float64:
			d.Set("last_updated_on", int64(n))
		case int:
			d.Set("last_updated_on", int64(n))
		case int64:
			d.Set("last_updated_on", n)
		}
	}
	if v, ok := raw["name"].(string); ok {
		d.Set("name", v)
	}
	if v, ok := raw["supportKeyWord"].(string); ok {
		d.Set("support_key_word", v)
	}
	if v, ok := raw["theme"].(string); ok {
		d.Set("theme", v)
	}
	if v, ok := raw["timescale"].(string); ok {
		d.Set("timescale", v)
	}
	if v, ok := raw["type"].(string); ok {
		d.Set("type", v)
	}
	if v, ok := raw["userPermission"].(string); ok {
		d.Set("user_permission", v)
	}
}

func SetWidgetResourceData(d *schema.ResourceData, raw map[string]interface{}) {
	setCommonWidgetFields(d, raw)
	typeValue, ok := raw["type"].(string)
	if !ok {
		return
	}
	switch typeValue {
	case "cgraph":
		if v, ok := raw["graphInfo"]; ok {
			d.Set("graph_info", []interface{}{apiMapToSnake(v)})
		}
	case "bigNumber":
		if v, ok := raw["bigNumberInfo"]; ok {
			d.Set("big_number_info", []interface{}{apiMapToSnake(v)})
		}
	case "pieChart":
		if v, ok := raw["pieChartInfo"]; ok {
			d.Set("pie_chart_info", []interface{}{apiMapToSnake(v)})
		}
	}
}

func FlattenWidgetPayload(d *schema.ResourceData) (map[string]interface{}, error) {
	payload := map[string]interface{}{}
	if v, err := getIntAttr(d, "dashboard_id"); err != nil {
		return nil, err
	} else {
		payload["dashboardId"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "description"); err != nil { return nil, err } else if ok {
		payload["description"] = v
	}
	if v, ok, err := getOptionalIntAttr(d, "interval"); err != nil { return nil, err } else if ok {
		payload["interval"] = v
	}
	if v, err := getStringAttr(d, "name"); err != nil {
		return nil, err
	} else {
		payload["name"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "support_key_word"); err != nil { return nil, err } else if ok {
		payload["supportKeyWord"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "theme"); err != nil { return nil, err } else if ok {
		payload["theme"] = v
	}
	if v, ok, err := getOptionalStringAttr(d, "timescale"); err != nil { return nil, err } else if ok {
		payload["timescale"] = v
	}
	if v, err := getStringAttr(d, "type"); err != nil {
		return nil, err
	} else {
		payload["type"] = v
	}
	typeValue, err := getTypeAttr(d)
	if err != nil {
		return nil, err
	}
	switch typeValue {
	case "cgraph":
		block, err := getSingleBlock(d, "graph_info")
		if err != nil {
			return nil, err
		}
		payload["graphInfo"] = tfBlockToAPI(block)
	case "bigNumber":
		block, err := getSingleBlock(d, "big_number_info")
		if err != nil {
			return nil, err
		}
		payload["bigNumberInfo"] = tfBlockToAPI(block)
	case "pieChart":
		block, err := getSingleBlock(d, "pie_chart_info")
		if err != nil {
			return nil, err
		}
		payload["pieChartInfo"] = tfBlockToAPI(block)
	default:
		return nil, fmt.Errorf("unsupported type: %s", typeValue)
	}
	return payload, nil
}
