// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AlertWidgetDisplaySettings alert widget display settings
//
// swagger:model AlertWidgetDisplaySettings
type AlertWidgetDisplaySettings struct {

	// columns
	Columns []*AlertWidgetColumn `json:"columns"`

	// fontsize
	Fontsize string `json:"fontsize,omitempty"`

	// is show all
	IsShowAll bool `json:"isShowAll,omitempty"`

	// play sound
	PlaySound *AlertWidgetPlaySoundSettings `json:"playSound,omitempty"`

	// show filter
	ShowFilter bool `json:"showFilter,omitempty"`

	// sort
	Sort string `json:"sort,omitempty"`
}

// Validate validates this alert widget display settings
func (m *AlertWidgetDisplaySettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateColumns(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlaySound(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AlertWidgetDisplaySettings) validateColumns(formats strfmt.Registry) error {
	if swag.IsZero(m.Columns) { // not required
		return nil
	}

	for i := 0; i < len(m.Columns); i++ {
		if swag.IsZero(m.Columns[i]) { // not required
			continue
		}

		if m.Columns[i] != nil {
			if err := m.Columns[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("columns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("columns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AlertWidgetDisplaySettings) validatePlaySound(formats strfmt.Registry) error {
	if swag.IsZero(m.PlaySound) { // not required
		return nil
	}

	if m.PlaySound != nil {
		if err := m.PlaySound.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playSound")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playSound")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this alert widget display settings based on the context it is used
func (m *AlertWidgetDisplaySettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateColumns(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePlaySound(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AlertWidgetDisplaySettings) contextValidateColumns(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Columns); i++ {

		if m.Columns[i] != nil {
			if err := m.Columns[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("columns" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("columns" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AlertWidgetDisplaySettings) contextValidatePlaySound(ctx context.Context, formats strfmt.Registry) error {

	if m.PlaySound != nil {
		if err := m.PlaySound.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("playSound")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("playSound")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AlertWidgetDisplaySettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertWidgetDisplaySettings) UnmarshalBinary(b []byte) error {
	var res AlertWidgetDisplaySettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
