// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AlertWidgetPlaySoundSettings alert widget play sound settings
//
// swagger:model AlertWidgetPlaySoundSettings
type AlertWidgetPlaySoundSettings struct {

	// critical alert audio file name
	CriticalAlertAudioFileName string `json:"criticalAlertAudioFileName,omitempty"`

	// error alert audio file name
	ErrorAlertAudioFileName string `json:"errorAlertAudioFileName,omitempty"`

	// should play
	ShouldPlay bool `json:"shouldPlay,omitempty"`

	// warning alert audio file name
	WarningAlertAudioFileName string `json:"warningAlertAudioFileName,omitempty"`
}

// Validate validates this alert widget play sound settings
func (m *AlertWidgetPlaySoundSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this alert widget play sound settings based on context it is used
func (m *AlertWidgetPlaySoundSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AlertWidgetPlaySoundSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertWidgetPlaySoundSettings) UnmarshalBinary(b []byte) error {
	var res AlertWidgetPlaySoundSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
