// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceNOCItem device n o c item
//
// swagger:model DeviceNOCItem
type DeviceNOCItem struct {
	dataPointNameField string

	dataSourceDisplayNameField string

	deviceDisplayNameField string

	deviceGroupFullPathField string

	groupByField string

	instanceNameField string

	nameField string

	nocItemOptionsField string

	websiteGroupNameField string

	websiteNameField string

	DeviceNOCItemAllOf1
}

// DataPointName gets the data point name of this subtype
func (m *DeviceNOCItem) DataPointName() string {
	return m.dataPointNameField
}

// SetDataPointName sets the data point name of this subtype
func (m *DeviceNOCItem) SetDataPointName(val string) {
	m.dataPointNameField = val
}

// DataSourceDisplayName gets the data source display name of this subtype
func (m *DeviceNOCItem) DataSourceDisplayName() string {
	return m.dataSourceDisplayNameField
}

// SetDataSourceDisplayName sets the data source display name of this subtype
func (m *DeviceNOCItem) SetDataSourceDisplayName(val string) {
	m.dataSourceDisplayNameField = val
}

// DeviceDisplayName gets the device display name of this subtype
func (m *DeviceNOCItem) DeviceDisplayName() string {
	return m.deviceDisplayNameField
}

// SetDeviceDisplayName sets the device display name of this subtype
func (m *DeviceNOCItem) SetDeviceDisplayName(val string) {
	m.deviceDisplayNameField = val
}

// DeviceGroupFullPath gets the device group full path of this subtype
func (m *DeviceNOCItem) DeviceGroupFullPath() string {
	return m.deviceGroupFullPathField
}

// SetDeviceGroupFullPath sets the device group full path of this subtype
func (m *DeviceNOCItem) SetDeviceGroupFullPath(val string) {
	m.deviceGroupFullPathField = val
}

// GroupBy gets the group by of this subtype
func (m *DeviceNOCItem) GroupBy() string {
	return m.groupByField
}

// SetGroupBy sets the group by of this subtype
func (m *DeviceNOCItem) SetGroupBy(val string) {
	m.groupByField = val
}

// InstanceName gets the instance name of this subtype
func (m *DeviceNOCItem) InstanceName() string {
	return m.instanceNameField
}

// SetInstanceName sets the instance name of this subtype
func (m *DeviceNOCItem) SetInstanceName(val string) {
	m.instanceNameField = val
}

// Name gets the name of this subtype
func (m *DeviceNOCItem) Name() string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *DeviceNOCItem) SetName(val string) {
	m.nameField = val
}

// NocItemOptions gets the noc item options of this subtype
func (m *DeviceNOCItem) NocItemOptions() string {
	return m.nocItemOptionsField
}

// SetNocItemOptions sets the noc item options of this subtype
func (m *DeviceNOCItem) SetNocItemOptions(val string) {
	m.nocItemOptionsField = val
}

// Type gets the type of this subtype
func (m *DeviceNOCItem) Type() string {
	return "DeviceNOCItem"
}

// SetType sets the type of this subtype
func (m *DeviceNOCItem) SetType(val string) {
}

// WebsiteGroupName gets the website group name of this subtype
func (m *DeviceNOCItem) WebsiteGroupName() string {
	return m.websiteGroupNameField
}

// SetWebsiteGroupName sets the website group name of this subtype
func (m *DeviceNOCItem) SetWebsiteGroupName(val string) {
	m.websiteGroupNameField = val
}

// WebsiteName gets the website name of this subtype
func (m *DeviceNOCItem) WebsiteName() string {
	return m.websiteNameField
}

// SetWebsiteName sets the website name of this subtype
func (m *DeviceNOCItem) SetWebsiteName(val string) {
	m.websiteNameField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *DeviceNOCItem) UnmarshalJSON(raw []byte) error {
	var data struct {
		DeviceNOCItemAllOf1
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		DataPointName string `json:"dataPointName,omitempty"`

		DataSourceDisplayName string `json:"dataSourceDisplayName,omitempty"`

		DeviceDisplayName string `json:"deviceDisplayName,omitempty"`

		DeviceGroupFullPath string `json:"deviceGroupFullPath,omitempty"`

		GroupBy string `json:"groupBy,omitempty"`

		InstanceName string `json:"instanceName,omitempty"`

		Name string `json:"name,omitempty"`

		NocItemOptions string `json:"nocItemOptions,omitempty"`

		Type string `json:"type"`

		WebsiteGroupName string `json:"websiteGroupName,omitempty"`

		WebsiteName string `json:"websiteName,omitempty"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result DeviceNOCItem

	result.dataPointNameField = base.DataPointName

	result.dataSourceDisplayNameField = base.DataSourceDisplayName

	result.deviceDisplayNameField = base.DeviceDisplayName

	result.deviceGroupFullPathField = base.DeviceGroupFullPath

	result.groupByField = base.GroupBy

	result.instanceNameField = base.InstanceName

	result.nameField = base.Name

	result.nocItemOptionsField = base.NocItemOptions

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}
	result.websiteGroupNameField = base.WebsiteGroupName

	result.websiteNameField = base.WebsiteName

	result.DeviceNOCItemAllOf1 = data.DeviceNOCItemAllOf1

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m DeviceNOCItem) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		DeviceNOCItemAllOf1
	}{

		DeviceNOCItemAllOf1: m.DeviceNOCItemAllOf1,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		DataPointName string `json:"dataPointName,omitempty"`

		DataSourceDisplayName string `json:"dataSourceDisplayName,omitempty"`

		DeviceDisplayName string `json:"deviceDisplayName,omitempty"`

		DeviceGroupFullPath string `json:"deviceGroupFullPath,omitempty"`

		GroupBy string `json:"groupBy,omitempty"`

		InstanceName string `json:"instanceName,omitempty"`

		Name string `json:"name,omitempty"`

		NocItemOptions string `json:"nocItemOptions,omitempty"`

		Type string `json:"type"`

		WebsiteGroupName string `json:"websiteGroupName,omitempty"`

		WebsiteName string `json:"websiteName,omitempty"`
	}{

		DataPointName: m.DataPointName(),

		DataSourceDisplayName: m.DataSourceDisplayName(),

		DeviceDisplayName: m.DeviceDisplayName(),

		DeviceGroupFullPath: m.DeviceGroupFullPath(),

		GroupBy: m.GroupBy(),

		InstanceName: m.InstanceName(),

		Name: m.Name(),

		NocItemOptions: m.NocItemOptions(),

		Type: m.Type(),

		WebsiteGroupName: m.WebsiteGroupName(),

		WebsiteName: m.WebsiteName(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this device n o c item
func (m *DeviceNOCItem) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DeviceNOCItemAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this device n o c item based on the context it is used
func (m *DeviceNOCItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DeviceNOCItemAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceNOCItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceNOCItem) UnmarshalBinary(b []byte) error {
	var res DeviceNOCItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DeviceNOCItemAllOf1 device n o c item all of1
//
// swagger:model DeviceNOCItemAllOf1
type DeviceNOCItemAllOf1 interface{}
