// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TableWidgetDisplaySettings table widget display settings
//
// swagger:model TableWidgetDisplaySettings
type TableWidgetDisplaySettings struct {

	// columns v4
	ColumnsV4 []*TableWidgetColumn `json:"columnsV4"`

	// override filter
	OverrideFilter bool `json:"overrideFilter,omitempty"`

	// page size
	PageSize string `json:"pageSize,omitempty"`

	// property columns
	PropertyColumns []string `json:"propertyColumns"`

	// show filter
	ShowFilter bool `json:"showFilter,omitempty"`
}

// Validate validates this table widget display settings
func (m *TableWidgetDisplaySettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateColumnsV4(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TableWidgetDisplaySettings) validateColumnsV4(formats strfmt.Registry) error {
	if swag.IsZero(m.ColumnsV4) { // not required
		return nil
	}

	for i := 0; i < len(m.ColumnsV4); i++ {
		if swag.IsZero(m.ColumnsV4[i]) { // not required
			continue
		}

		if m.ColumnsV4[i] != nil {
			if err := m.ColumnsV4[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("columnsV4" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("columnsV4" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this table widget display settings based on the context it is used
func (m *TableWidgetDisplaySettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateColumnsV4(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TableWidgetDisplaySettings) contextValidateColumnsV4(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ColumnsV4); i++ {

		if m.ColumnsV4[i] != nil {
			if err := m.ColumnsV4[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("columnsV4" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("columnsV4" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TableWidgetDisplaySettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TableWidgetDisplaySettings) UnmarshalBinary(b []byte) error {
	var res TableWidgetDisplaySettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
