// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebsiteLocation website location
//
// swagger:model WebsiteLocation
type WebsiteLocation struct {

	// all
	// Example: true
	All bool `json:"all"`

	// collector ids
	CollectorIds []int32 `json:"collectorIds"`

	// smg ids
	// Example: [1, 2, 4, 3, 5, 6]
	SmgIds []int32 `json:"smgIds"`
}

// Validate validates this website location
func (m *WebsiteLocation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this website location based on context it is used
func (m *WebsiteLocation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebsiteLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebsiteLocation) UnmarshalBinary(b []byte) error {
	var res WebsiteLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
