// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WidgetVariantNocFlat Auto-generated flat API model
//
// swagger:model WidgetVariantNocFlat
type WidgetVariantNocFlat struct {

	// Whether or not acknowledgements are displayed in the NOC widget, the default value is true
	AckChecked bool `json:"ackChecked,omitempty"`

	// clone widget Id
	CloneWidgetID int32 `json:"cloneWidgetId,omitempty"`

	// The id of the dashboard the widget belongs to
	// Example: 1
	// Required: true
	DashboardID *int32 `json:"dashboardId"`

	// The description of the widget
	// Example: Devices By Type
	Description string `json:"description,omitempty"`

	// The maximum number columns displayed in the NOC widget
	DisplayColumn int32 `json:"displayColumn,omitempty"`

	// Whether or not critical alerts are displayed in the NOC widget, the default value is true
	DisplayCriticalAlert bool `json:"displayCriticalAlert,omitempty"`

	// Whether or not error alerts are displayed in the NOC widget, the default value is true
	DisplayErrorAlert bool `json:"displayErrorAlert,omitempty"`

	// Serialized JSON for NOC widget display settings
	DisplaySettings string `json:"displaySettings,omitempty"`

	// Whether or not warning alerts are displayed in the NOC widget, the default value is true
	DisplayWarnAlert bool `json:"displayWarnAlert,omitempty"`

	// The Id of the widget
	ID int32 `json:"id,omitempty"`

	// The refresh interval of the widget, in minutes
	// Example: 5
	Interval int32 `json:"interval,omitempty"`

	// is support custom property
	IsSupportCustomProperty bool `json:"isSupportCustomProperty,omitempty"`

	itemsField []NOCItemBase

	// The name of the widget
	// Example: Test
	// Required: true
	Name *string `json:"name"`

	// Whether or not SDTs are displayed in the NOC widget, the default value is true
	SdtChecked bool `json:"sdtChecked,omitempty"`

	// How NOC items are sorted
	SortBy string `json:"sortBy,omitempty"`

	// support custom property
	SupportCustomProperty bool `json:"supportCustomProperty,omitempty"`

	// The support keyword associated with the widget type (e.g. Pie Chart)
	SupportKeyWord string `json:"supportKeyWord,omitempty"`

	// The color scheme of the widget. Options are: borderPurple | borderGray | borderBlue | solidPurple | solidGray | solidBlue | simplePurple | simpleBlue | simpleGray | newBorderGray | newBorderBlue | newBorderDarkBlue | newSolidGray | newSolidBlue | newSolidDarkBlue | newSimpleGray | newSimpleBlue |newSimpleDarkBlue
	// Example: newBorderBlue
	Theme string `json:"theme,omitempty"`

	// The default timescale of the widget
	Timescale string `json:"timescale,omitempty"`

	// alert | batchjob | flash | gmap | ngraph | ograph | cgraph | sgraph | netflowgraph | groupNetflowGraph | netflow | groupNetflow | html | bigNumber | gauge | pieChart | table | dynamicTable | deviceSLA | text | statsd | deviceStatus | serviceAlert | noc | websiteOverview | websiteOverallStatus | websiteIndividualStatus | websiteSLA
	// Example: bigNumber
	// Required: true
	Type *string `json:"type"`

	// Serialized JSON for NOC widget filters
	WidgetFilters string `json:"widgetFilters,omitempty"`
}

// Items gets the items of this base type
func (m *WidgetVariantNocFlat) Items() []NOCItemBase {
	return m.itemsField
}

// SetItems sets the items of this base type
func (m *WidgetVariantNocFlat) SetItems(val []NOCItemBase) {
	m.itemsField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *WidgetVariantNocFlat) UnmarshalJSON(raw []byte) error {
	var data struct {
		AckChecked bool `json:"ackChecked,omitempty"`

		CloneWidgetID int32 `json:"cloneWidgetId,omitempty"`

		DashboardID *int32 `json:"dashboardId"`

		Description string `json:"description,omitempty"`

		DisplayColumn int32 `json:"displayColumn,omitempty"`

		DisplayCriticalAlert bool `json:"displayCriticalAlert,omitempty"`

		DisplayErrorAlert bool `json:"displayErrorAlert,omitempty"`

		DisplaySettings string `json:"displaySettings,omitempty"`

		DisplayWarnAlert bool `json:"displayWarnAlert,omitempty"`

		ID int32 `json:"id,omitempty"`

		Interval int32 `json:"interval,omitempty"`

		IsSupportCustomProperty bool `json:"isSupportCustomProperty,omitempty"`

		Items json.RawMessage `json:"items"`

		Name *string `json:"name"`

		SdtChecked bool `json:"sdtChecked,omitempty"`

		SortBy string `json:"sortBy,omitempty"`

		SupportCustomProperty bool `json:"supportCustomProperty,omitempty"`

		SupportKeyWord string `json:"supportKeyWord,omitempty"`

		Theme string `json:"theme,omitempty"`

		Timescale string `json:"timescale,omitempty"`

		Type *string `json:"type"`

		WidgetFilters string `json:"widgetFilters,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	propItems, err := UnmarshalNOCItemBaseSlice(bytes.NewBuffer(data.Items), runtime.JSONConsumer())
	if err != nil && err != io.EOF {
		return err
	}

	var result WidgetVariantNocFlat

	// ackChecked
	result.AckChecked = data.AckChecked

	// cloneWidgetId
	result.CloneWidgetID = data.CloneWidgetID

	// dashboardId
	result.DashboardID = data.DashboardID

	// description
	result.Description = data.Description

	// displayColumn
	result.DisplayColumn = data.DisplayColumn

	// displayCriticalAlert
	result.DisplayCriticalAlert = data.DisplayCriticalAlert

	// displayErrorAlert
	result.DisplayErrorAlert = data.DisplayErrorAlert

	// displaySettings
	result.DisplaySettings = data.DisplaySettings

	// displayWarnAlert
	result.DisplayWarnAlert = data.DisplayWarnAlert

	// id
	result.ID = data.ID

	// interval
	result.Interval = data.Interval

	// isSupportCustomProperty
	result.IsSupportCustomProperty = data.IsSupportCustomProperty

	// items
	result.itemsField = propItems

	// name
	result.Name = data.Name

	// sdtChecked
	result.SdtChecked = data.SdtChecked

	// sortBy
	result.SortBy = data.SortBy

	// supportCustomProperty
	result.SupportCustomProperty = data.SupportCustomProperty

	// supportKeyWord
	result.SupportKeyWord = data.SupportKeyWord

	// theme
	result.Theme = data.Theme

	// timescale
	result.Timescale = data.Timescale

	// type
	result.Type = data.Type

	// widgetFilters
	result.WidgetFilters = data.WidgetFilters

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m WidgetVariantNocFlat) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		AckChecked bool `json:"ackChecked,omitempty"`

		CloneWidgetID int32 `json:"cloneWidgetId,omitempty"`

		DashboardID *int32 `json:"dashboardId"`

		Description string `json:"description,omitempty"`

		DisplayColumn int32 `json:"displayColumn,omitempty"`

		DisplayCriticalAlert bool `json:"displayCriticalAlert,omitempty"`

		DisplayErrorAlert bool `json:"displayErrorAlert,omitempty"`

		DisplaySettings string `json:"displaySettings,omitempty"`

		DisplayWarnAlert bool `json:"displayWarnAlert,omitempty"`

		ID int32 `json:"id,omitempty"`

		Interval int32 `json:"interval,omitempty"`

		IsSupportCustomProperty bool `json:"isSupportCustomProperty,omitempty"`

		Name *string `json:"name"`

		SdtChecked bool `json:"sdtChecked,omitempty"`

		SortBy string `json:"sortBy,omitempty"`

		SupportCustomProperty bool `json:"supportCustomProperty,omitempty"`

		SupportKeyWord string `json:"supportKeyWord,omitempty"`

		Theme string `json:"theme,omitempty"`

		Timescale string `json:"timescale,omitempty"`

		Type *string `json:"type"`

		WidgetFilters string `json:"widgetFilters,omitempty"`
	}{

		AckChecked: m.AckChecked,

		CloneWidgetID: m.CloneWidgetID,

		DashboardID: m.DashboardID,

		Description: m.Description,

		DisplayColumn: m.DisplayColumn,

		DisplayCriticalAlert: m.DisplayCriticalAlert,

		DisplayErrorAlert: m.DisplayErrorAlert,

		DisplaySettings: m.DisplaySettings,

		DisplayWarnAlert: m.DisplayWarnAlert,

		ID: m.ID,

		Interval: m.Interval,

		IsSupportCustomProperty: m.IsSupportCustomProperty,

		Name: m.Name,

		SdtChecked: m.SdtChecked,

		SortBy: m.SortBy,

		SupportCustomProperty: m.SupportCustomProperty,

		SupportKeyWord: m.SupportKeyWord,

		Theme: m.Theme,

		Timescale: m.Timescale,

		Type: m.Type,

		WidgetFilters: m.WidgetFilters,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Items []NOCItemBase `json:"items"`
	}{

		Items: m.itemsField,
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this widget variant noc flat
func (m *WidgetVariantNocFlat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDashboardID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetVariantNocFlat) validateDashboardID(formats strfmt.Registry) error {

	if err := validate.Required("dashboardId", "body", m.DashboardID); err != nil {
		return err
	}

	return nil
}

func (m *WidgetVariantNocFlat) validateItems(formats strfmt.Registry) error {

	if err := validate.Required("items", "body", m.Items()); err != nil {
		return err
	}

	for i := 0; i < len(m.Items()); i++ {

		if err := m.itemsField[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("items" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("items" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *WidgetVariantNocFlat) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *WidgetVariantNocFlat) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this widget variant noc flat based on the context it is used
func (m *WidgetVariantNocFlat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetVariantNocFlat) contextValidateItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Items()); i++ {

		if err := m.itemsField[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("items" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("items" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WidgetVariantNocFlat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetVariantNocFlat) UnmarshalBinary(b []byte) error {
	var res WidgetVariantNocFlat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
