// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WidgetRefreshFrequency widget refresh frequency
//
// swagger:model WidgetRefreshFrequency
type WidgetRefreshFrequency struct {

	// offset
	Offset int32 `json:"offset,omitempty"`

	// units
	Units string `json:"units,omitempty"`
}

// Validate validates this widget refresh frequency
func (m *WidgetRefreshFrequency) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this widget refresh frequency based on context it is used
func (m *WidgetRefreshFrequency) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WidgetRefreshFrequency) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetRefreshFrequency) UnmarshalBinary(b []byte) error {
	var res WidgetRefreshFrequency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
