// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WidgetVariantAlertFlat Auto-generated flat API model
//
// swagger:model WidgetVariantAlertFlat
type WidgetVariantAlertFlat struct {

	// clone widget Id
	CloneWidgetID int32 `json:"cloneWidgetId,omitempty"`

	// The id of the dashboard the widget belongs to
	// Example: 1
	// Required: true
	DashboardID *int32 `json:"dashboardId"`

	// The description of the widget
	// Example: Devices By Type
	Description string `json:"description,omitempty"`

	// Serialized JSON for alert widget display settings
	DisplaySettings string `json:"displaySettings,omitempty"`

	// The filter for the alert table
	Filters *AlertFilters `json:"filters,omitempty"`

	// The Id of the widget
	ID int32 `json:"id,omitempty"`

	// The refresh interval of the widget, in minutes
	// Example: 5
	Interval int32 `json:"interval,omitempty"`

	// is support custom property
	IsSupportCustomProperty bool `json:"isSupportCustomProperty,omitempty"`

	// The name of the widget
	// Example: Test
	// Required: true
	Name *string `json:"name"`

	// parsed filters
	ParsedFilters *AlertFilters `json:"parsedFilters,omitempty"`

	// Serialized JSON for alert widget refresh frequency settings
	RefreshFrequency string `json:"refreshFrequency,omitempty"`

	// support custom property
	SupportCustomProperty bool `json:"supportCustomProperty,omitempty"`

	// The support keyword associated with the widget type (e.g. Pie Chart)
	SupportKeyWord string `json:"supportKeyWord,omitempty"`

	// The color scheme of the widget. Options are: borderPurple | borderGray | borderBlue | solidPurple | solidGray | solidBlue | simplePurple | simpleBlue | simpleGray | newBorderGray | newBorderBlue | newBorderDarkBlue | newSolidGray | newSolidBlue | newSolidDarkBlue | newSimpleGray | newSimpleBlue |newSimpleDarkBlue
	// Example: newBorderBlue
	Theme string `json:"theme,omitempty"`

	// The default timescale of the widget
	Timescale string `json:"timescale,omitempty"`

	// alert | batchjob | flash | gmap | ngraph | ograph | cgraph | sgraph | netflowgraph | groupNetflowGraph | netflow | groupNetflow | html | bigNumber | gauge | pieChart | table | dynamicTable | deviceSLA | text | statsd | deviceStatus | serviceAlert | noc | websiteOverview | websiteOverallStatus | websiteIndividualStatus | websiteSLA
	// Example: bigNumber
	// Required: true
	Type *string `json:"type"`

	// widget color schema
	WidgetColorSchema string `json:"widgetColorSchema,omitempty"`
}

// Validate validates this widget variant alert flat
func (m *WidgetVariantAlertFlat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDashboardID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParsedFilters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetVariantAlertFlat) validateDashboardID(formats strfmt.Registry) error {

	if err := validate.Required("dashboardId", "body", m.DashboardID); err != nil {
		return err
	}

	return nil
}

func (m *WidgetVariantAlertFlat) validateFilters(formats strfmt.Registry) error {
	if swag.IsZero(m.Filters) { // not required
		return nil
	}

	if m.Filters != nil {
		if err := m.Filters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filters")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filters")
			}
			return err
		}
	}

	return nil
}

func (m *WidgetVariantAlertFlat) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *WidgetVariantAlertFlat) validateParsedFilters(formats strfmt.Registry) error {
	if swag.IsZero(m.ParsedFilters) { // not required
		return nil
	}

	if m.ParsedFilters != nil {
		if err := m.ParsedFilters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parsedFilters")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parsedFilters")
			}
			return err
		}
	}

	return nil
}

func (m *WidgetVariantAlertFlat) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this widget variant alert flat based on the context it is used
func (m *WidgetVariantAlertFlat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParsedFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetVariantAlertFlat) contextValidateFilters(ctx context.Context, formats strfmt.Registry) error {

	if m.Filters != nil {
		if err := m.Filters.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filters")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filters")
			}
			return err
		}
	}

	return nil
}

func (m *WidgetVariantAlertFlat) contextValidateParsedFilters(ctx context.Context, formats strfmt.Registry) error {

	if m.ParsedFilters != nil {
		if err := m.ParsedFilters.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parsedFilters")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parsedFilters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WidgetVariantAlertFlat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetVariantAlertFlat) UnmarshalBinary(b []byte) error {
	var res WidgetVariantAlertFlat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
